### PR TITLE
Support hosted domains and fix for URI routed APIs

### PR DESCRIPTION
**Pull request by XVincentX**
The following PR will implement the hosted domain feature - which is basically the idea of restricting the login in order to be valid only for some domains. This is imitating the same (custom) feature that Google is giving you out of the box (in both OAuth 1 and 2).

This is particularly useful if you're on a thirty party mail system through your domain which provides free services (or generic OAuth service) as well.

I'm not really familiar with the lua ecosystem, thus I am not entirely sure how to release or bump the version (as I can see 3 different spec files). Any help here would be appreciated.

### CODE REVIEW

**Comment by XVincentX** [comment]
@mogui I've also added another commit that will fix the support for Uris routed APIs.
It seems like it wasn't working properly anymore (probably because the `ngx.ctx.api` object changed). The changes are in 69e7a4c

**Comment by mogui** [comment]
Hi Vincent sorry to be late, merging it now

**Comment by XVincentX** [comment]
Thanks for merging; I think it needs to be published on luarocks as well, but I'll leave that up to you!

**Comment by mogui** [comment]
Yeah it needs, I have to figure out what's wrong with luarocks I have a astrange issue on that.
Anyway I'll be doing it :)

**Comment by XVincentX** [comment]
Thank you - I'l really looking forward to see this live!

**Pull request merged**
